services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: image-lecture-seo-llm_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  web:
    build: .
    container_name: image-lecture-seo-api
    restart: always
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  ollama_data: